parameters:
    innomatic_legacy.router.class: Innomatic\Bundle\InnomaticLegacyBundle\Routing\LegacyRouter
    innomatic_legacy.controller.class: Innomatic\Bundle\InnomaticLegacyBundle\Controller\LegacyKernelController
    innomatic_legacy.kernel.class: Innomatic\Core\MVC\Legacy\Kernel
    
services:
    innomatic_legacy.kernel:
        class: %innomatic_legacy.kernel.class%

    innomatic_legacy.router:
        class: %innomatic_legacy.router.class%
        arguments: [@?request_context, @?logger]
        tags:
            - {name: router, priority: -255}
        lazy: true

    innomatic_legacy.controller:
        class: %innomatic_legacy.controller.class%
        arguments:
            - @router
        calls:
            - [setRequest, [@?request=]]
            - [setContainer, [@service_container]]